<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Handle a Rejected Promise with catch</title>
  </head>
  <body>

  <script>

    /*
    * [catch] is the method used when your promise has been rejected.
    * It is executed immediately after a promise's [reject] method called.
    */

    // Example
    myPromise.catch(error => {
      // do something with the error.
    });

    /*
    * [error] is the argument passed into [reject] method.
    */

    /*
    * NOTE:
    * the [then] and [catch] methods can be chained to the promise declaration if you choose.
    */

    const makeServerRequest = new Promise((resolve, reject) => {
      // responseFromServer is set to false to represent an unsuccessful response from a server
      let responseFromServer = false;
        
      if(responseFromServer) {
        resolve("We got the data");
      } else {
        reject("Data not received");
      }
    });

    makeServerRequest.then(result => {
      console.log(result);
    });

    makeServerRequest.catch(error => {
      console.log(error);
    });

  </script>
  </body>
</html>
